### ISSUE TITLE
Arabic titles are capitalized

### ISSUE THREAD

**Issue by pverkind** [kitab-project-org/ZoteroStyleForKITAB#3]
Desired behavior: capitalization of titles should be kept as it is in the database.
Now, "Laḥẓ al-alḥāẓ bi-dhayl Ṭabaqāt al-ḥuffāẓ" is inserted as "Laḥẓ Al-Alḥāẓ Bi-Dhayl Ṭabaqāt al-Ḥuffāẓ"

**Comment by maximromanov** [comment]
If you change the language of publication to Arabic, it should stop capitalizing

**Comment by pverkind** [comment]
wow, this is great, thanks, Maxim!
